package test;

import static org.junit.Assert.*;
import java.io.*;
import org.junit.Test;

/** Class automatically generated by YETI **/
public class YetiTests {

   /** Test case automatically generated by YETI **/
   @Test public void test_0() throws Exception {
      byte []v4_bytes={};// class is not serializable, toString() returns: example.A@1f599ef
      example.A v4=(example.A)(new ObjectInputStream(new ByteArrayInputStream(v4_bytes)).readObject());
      example.YetiExample.illustrateAssertion((example.A)v4);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.AssertionError
      	at example.YetiExample.illustrateAssertion(YetiExample.java:62)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_1() throws Exception {
      example.YetiExample.illustrateUnusableConstructor((example.B)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at example.YetiExample.illustrateUnusableConstructor(YetiExample.java:31)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_2() throws Exception {
      example.YetiExample.illustrateRandomPlus((int)4);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.ArrayIndexOutOfBoundsException: 4
      	at example.YetiExample.illustrateRandomPlus(YetiExample.java:56)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_3() throws Exception {
      byte []v28_bytes={};// class is not serializable, toString() returns: example.YetiExample@3a157e
      example.YetiExample v28=(example.YetiExample)(new ObjectInputStream(new ByteArrayInputStream(v28_bytes)).readObject());
      v28.illustrateRelevantValues((java.lang.String)null,(int)16520985);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at example.YetiExample.illustrateRelevantValues(YetiExample.java:66)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_4() throws Exception {
      example.YetiExample.illustrateBadConstructor((example.A)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at example.YetiExample.illustrateBadConstructor(YetiExample.java:23)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_5() throws Exception {
      byte []v283_bytes={};// class is not serializable, toString() returns: example.A@1fdc730
      example.A v283=(example.A)(new ObjectInputStream(new ByteArrayInputStream(v283_bytes)).readObject());
      example.YetiExample.illustrateBadConstructor((example.A)v283);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.NullPointerException
      	at example.A.useC(A.java:24)
      	at example.YetiExample.illustrateBadConstructor(YetiExample.java:23)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_6() throws Exception {
      example.YetiExample.illustrateExactValue((int)1337);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.ArithmeticException: / by zero
      	at example.YetiExample.illustrateExactValue(YetiExample.java:19)**/
   
   }


   /** Test case automatically generated by YETI **/
   @Test public void test_7() throws Exception {
      byte []v94255_bytes={(byte)-84,(byte)-19,(byte)0,(byte)5,(byte)116,(byte)0,(byte)11,(byte)112,(byte)114,(byte)105,(byte)110,(byte)116,(byte)95,(byte)99,(byte)111,(byte)108,(byte)111,(byte)114};
      java.lang.String v94255=(java.lang.String)(new ObjectInputStream(new ByteArrayInputStream(v94255_bytes)).readObject());
      byte []v84287_bytes={};// class is not serializable, toString() returns: example.YetiExample@a5ae63
      example.YetiExample v84287=(example.YetiExample)(new ObjectInputStream(new ByteArrayInputStream(v84287_bytes)).readObject());
      v84287.illustrateRelevantValues((java.lang.String)v94255,(int)4);
      /**BUG FOUND: RUNTIME EXCEPTION**/
      /** java.lang.ArrayIndexOutOfBoundsException: 4
      	at example.YetiExample.illustrateRelevantValues(YetiExample.java:68)**/
   
   }


}